### ISSUE TITLE
No service-worker.js file in dev environment

### ISSUE THREAD

**Issue by aganglada** [codebusking/next-hnpwa-guide-app#10]
I'm getting an error when trying to run my app in development environment:

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOENT: no such file or directory, open './.next/service-worker.js'`

when running: `NODE_ENV=development node server.js`

**Comment by ragingwind** [comment]
refer to https://github.com/codebusking/next-hnpwa-guide-app/issues/3
