### ISSUE TITLE
build: Using next dev without Service worker

### ISSUE THREAD

**Issue by ragingwind** [codebusking/next-hnpwa-guide-app#3]
This app fetch items via firebase-hackernews running on sw, therefore sw must be run every time. But it's a bother as make up UI

**Comment by aganglada** [comment]
Is this referring to the fact there is no `yarn dev` and because of that no service worker is running on dev? Could you help on this? Thanks!

**Comment by ragingwind** [comment]
@aganglada Sorry, no way to support sw in dev

**Comment by ragingwind** [comment]
I will make a new version with Next.js, workbox 3 and newer APIs for HNnews, which version might have dev mode. Thanks

**Comment by MichelDiz** [comment]
So `GET http://localhost:9000/static/manifest/manifest.json 404 (Not Found)`

I spent some time looking at this, thinking it was something wrong. So in DEV mode there is no way to test with LightHouse?

![captura de tela 2018-04-08 as 16 27 51](https://user-images.githubusercontent.com/6570955/38471618-deb9114c-3b49-11e8-90ad-79f480196c08.png)

**Comment by ragingwind** [comment]
@MichelDiz It might that you skipped to run `build` script. manifest will be generated in build time. and more, I don't recommend that testing pwa in dev mode. dev mode is only for developing ui and logic in app.
