### ISSUE TITLE
Error when direct navigation to url 

### ISSUE THREAD

**Issue by chulian1819** [codebusking/next-hnpwa-guide-app#8]
Any url beside the root shows an error, example:
https://next-hnpwa.now.sh/new

![image](https://user-images.githubusercontent.com/4574893/33046096-a330f09e-cea3-11e7-986b-99482d4bae14.png)

**Comment by ragingwind** [comment]
It's slightly purpose. I will update it with a new function. I'm going to close this. Thanks you
